name: Build and deploy ASP.Net Core app to Azure Web App - apiemails

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        # Definindo o diretório de saída como ./published-app
        run: dotnet publish --configuration Release --output ./published-app

      - name: Verify published files
        run: dir ./published-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: published-app-artifact
          path: ./published-app  # Certifique-se de que este caminho está correto

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: published-app-artifact  # Nome deve ser o mesmo do upload

      - name: Verify downloaded files
        run: dir ./published-app  # Verificar se os arquivos foram baixados corretamente

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56027922C8474C41BB2B521ED883B2C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B95BA2B91C2F43119DCCC09C6A0548A5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_67DC5DCA5B0E43E5A4EE7015F97EFEB1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'apiemails'
          slot-name: 'Production'
          package: ./published-app  # Certifique-se de que o caminho está correto e consistente
